import { useState } from 'react';
import './App.css';

function App() {
  const [prdFile, setPrdFile] = useState(null);
  const [prdFileName, setPrdFileName] = useState('');
  const [groqKey, setGroqKey] = useState('');
  const [testTypes, setTestTypes] = useState([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedTestPlan, setGeneratedTestPlan] = useState('');
  const [generatedTestCases, setGeneratedTestCases] = useState('');
  const [isLoadedFromEnv, setIsLoadedFromEnv] = useState(false);
  const [loadError, setLoadError] = useState('');

  // Available test types for multiselect
  const availableTestTypes = [
    { value: 'positive', label: 'Positive Test Cases' },
    { value: 'negative', label: 'Negative Test Cases' },
    { value: 'boundary', label: 'Boundary Value Analysis' },
    { value: 'equivalence', label: 'Equivalence Partitioning' },
    { value: 'decisionTable', label: 'Decision Table Testing' },
    { value: 'stateTransition', label: 'State Transition Testing' }
  ];

  // Load GROQ key from localStorage (simulating .env file)
  const loadGroqKeyFromStorage = () => {
    try {
      const savedKey = localStorage.getItem('vite_groq_key');
      if (savedKey) {
        setGroqKey(savedKey);
        setIsLoadedFromEnv(true);
        setLoadError('');
      } else {
        setLoadError('No GROQ key found in storage. Please enter it below.');
      }
    } catch (error) {
      setLoadError('Error loading GROQ key from storage.');
    }
  };

  // Save GROQ key to localStorage (simulating updating .env file)
  const saveGroqKeyToStorage = (key) => {
    try {
      localStorage.setItem('vite_groq_key', key);
      setGroqKey(key);
      setIsLoadedFromEnv(true);
      setLoadError('GROQ key saved successfully!');
    } catch (error) {
      setLoadError('Error saving GROQ key to storage.');
    }
  };

  // Handle file upload
  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setPrdFile(file);
      setPrdFileName(file.name);
      // Reset generated content when new file is uploaded
      setGeneratedTestPlan('');
      setGeneratedTestCases('');
    }
  };

  // Handle test type selection change
  const handleTestTypeChange = (selectedValues) => {
    setTestTypes(selectedValues);
  };

  // Mock function to generate test plan (in real app, this would call GROQ API)
  const generateTestPlan = () => {
    if (!prdFile || !groqKey || testTypes.length === 0) {
      alert('Please upload a PRD file, enter GROQ key, and select test types');
      return;
    }

    setIsGenerating(true);

    // Simulate API call delay
    setTimeout(() => {
      const testPlan = `# Test Plan for ${prdFileName}

## Overview
This test plan was generated based on the PRD document: ${prdFileName}

## Scope
- Test types selected: ${testTypes.map(t =>
  availableTestTypes.find(at => at.value === t)?.label || t
).join(', ')}

## Objectives
To validate the functionality described in the PRD document using appropriate test techniques.

## Approach
- Test design techniques: ${testTypes.includes('equivalence') ? 'Equivalence Partitioning, ' : ''}${testTypes.includes('boundary') ? 'Boundary Value Analysis, ' : ''}${testTypes.includes('decisionTable') ? 'Decision Table Testing, ' : ''}${testTypes.includes('stateTransition') ? 'State Transition Testing, ' : ''}
- Test levels: Unit, Integration, System
- Test types: ${testTypes.includes('positive') ? 'Functional (Positive), ' : ''}${testTypes.includes('negative') ? 'Functional (Negative), ' : ''}

## Resources
- Test environment: To be configured
- Tools: Test management system, defect tracking tool

## Schedule
- Test design: [To be scheduled]
- Test execution: [To be scheduled]
- Test reporting: [To be scheduled]

## Risks and Mitigations
- Risk: Incomplete requirements understanding
  Mitigation: Review PRD with stakeholders
- Risk: Test environment delays
  Mitigation: Early environment preparation

## Approvals
[To be filled by stakeholders]

---
*Generated by B.L.A.S.T. Test Case Generator*
*GROQ API Key: ${groqKey.substring(0, 8)}...${groqKey.slice(-4)}`;

      setGeneratedTestPlan(testPlan);
      setIsGenerating(false);
    }, 1500); // Simulate 1.5 second API call
  };

  // Mock function to generate test cases (in real app, this would call GROQ API)
  const generateTestCases = () => {
    if (!prdFile || !groqKey || testTypes.length === 0) {
      alert('Please upload a PRD file, enter GROQ key, and select test types');
      return;
    }

    setIsGenerating(true);

    // Simulate API call delay
    setTimeout(() => {
      const testCases = `# Test Cases for ${prdFileName}

## Test Case Summary
Total Test Cases: ${testTypes.length * 3} (3 per selected test type)

## Detailed Test Cases

${testTypes.map((type, index) => {
  const typeLabel = availableTestTypes.find(at => at.value === type)?.label || type;
  return `
### Test Case Set ${index + 1}: ${typeLabel}

**TC-${String(index + 1).padStart(3, '0')}-01**
- **Title:** Validate basic functionality
- **Precondition:** System is ready and PRD requirements understood
- **Test Steps:**
  1. Navigate to the feature module
  2. Perform primary action as described in PRD
  3. Verify expected outcome
- **Expected Result:** Feature works as specified in PRD
- **Actual Result:** [To be filled during execution]
- **Status:** [Pass/Fail/Blocked]
- **Remarks:** [Any observations]

**TC-${String(index + 1).padStart(3, '0')}-02**
- **Title:** Validate error handling
- **Precondition:** System is ready
- **Test Steps:**
  1. Navigate to the feature module
  2. Perform invalid action
  3. Verify system responds appropriately
- **Expected Result:** Proper error messages displayed
- **Actual Result:** [To be filled during execution]
- **Status:** [Pass/Fail/Blocked]
- **Remarks:** [Any observations]

**TC-${String(index + 1).padStart(3, '0')}-03**
- **Title:** Validate edge cases
- **Precondition:** System is ready
- **Test Steps:**
  1. Navigate to the feature module
  2. Test boundary/edge conditions
  3. Verify system behavior
- **Expected Result:** System handles edge cases correctly
- **Actual Result:** [To be filled during execution]
- **Status:** [Pass/Fail/Blocked]
- **Remarks:** [Any observations]
`;
}).join('\n')}

## Test Data
[To be prepared based on PRD specifications]

## Execution Schedule
[To be determined based on test plan]

## Exit Criteria
- All test cases executed
- No critical defects outstanding
- All blockers resolved

---
*Generated by B.L.A.S.T. Test Case Generator*
*GROQ API Key: ${groqKey.substring(0, 8)}...${groqKey.slice(-4)}`;

      setGeneratedTestCases(testCases);
      setIsGenerating(false);
    }, 2000); // Simulate 2 second API call
  };

  // Handle download of test plan
  const downloadTestPlan = () => {
    if (!generatedTestPlan) {
      alert('No test plan generated yet');
      return;
    }

    const blob = new Blob([generatedTestPlan], { type: 'text/markdown' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `test-plan-${prdFileName.replace(/\.[^/.]+$/, '')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  // Handle download of test cases
  const downloadTestCases = () => {
    if (!generatedTestCases) {
      alert('No test cases generated yet');
      return;
    }

    const blob = new Blob([generatedTestCases], { type: 'text/markdown' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `test-cases-${prdFileName.replace(/\.[^/.]+$/, '')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="App">
      <header className="app-header">
        <h1>B.L.A.S.T. Test Case Generator</h1>
        <p>Generate ISTQB/ISO-compliant test cases from PRD documents</p>
      </header>

      <main className="app-main">
        <div className="settings-panel">
          <div className="settings-section">
            <h2>📄 PRD Document</h2>
            <div className="file-upload">
              <input
                type="file"
                accept=".pdf,.doc,.docx,.txt"
                onChange={handleFileChange}
                disabled={isGenerating}
              />
              {prdFileName ? (
                <span className="file-selected">Selected: {prdFileName}</span>
              ) : (
                <span className="file-placeholder">Choose a PRD file from PRD folder</span>
              )}
            </div>
          </div>

          <div className="settings-section">
            <h2>🔑 GROQ API Settings</h2>
            <div className="env-status">
              {isLoadedFromEnv ? (
                <span className="status-success">✅ GROQ key loaded from storage</span>
              ) : (
                <span className="status-warning">⚠️ No GROQ key in storage</span>
              )}
              {loadError && <span className="status-error">{loadError}</span>}
            </div>
            <div className="key-input">
              <label htmlFor="groq-key">GROQ API Key:</label>
              <input
                type="password"
                id="groq-key"
                value={groqKey}
                onChange={(e) => setGroqKey(e.target.value)}
                placeholder="Enter your GROQ API key"
                disabled={isGenerating}
              />
              <div className="key-buttons">
                <button
                  onClick={loadGroqKeyFromStorage}
                  disabled={isGenerating}
                  className="btn-secondary"
                >
                  Load from Storage (.env)
                </button>
                <button
                  onClick={() => saveGroqKeyToStorage(groqKey)}
                  disabled={!groqKey || isGenerating}
                  className="btn-primary"
                >
                  Save to Storage (.env)
                </button>
              </div>
            </div>
          </div>

          <div className="settings-section">
            <h2>📋 Test Case Selection</h2>
            <div className="multiselect">
              <label>Select Test Types:</label>
              <div className="checkbox-group">
                {availableTestTypes.map((option) => (
                  <label key={option.value} className="checkbox-label">
                    <input
                      type="checkbox"
                      value={option.value}
                      checked={testTypes.includes(option.value)}
                      onChange={(e) => {
                        const updatedTypes = e.target.checked
                          ? [...testTypes, option.value]
                          : testTypes.filter(t => t !== option.value);
                        setTestTypes(updatedTypes);
                      }}
                      disabled={isGenerating}
                    />
                    <span>{option.label}</span>
                  </label>
                ))}
              </div>
              {testTypes.length > 0 && (
                <span className="selected-count">
                  {testTypes.length} test type(s) selected
                </span>
              )}
            </div>
          </div>
        </div>

        <div className="action-panel">
          <button
            onClick={generateTestPlan}
            disabled={isGenerating || !prdFile || !groqKey || testTypes.length === 0}
            className="btn-action"
          >
            {isGenerating ? 'Generating Test Plan...' : 'Generate Test Plan'}
          </button>

          <button
            onClick={generateTestCases}
            disabled={isGenerating || !prdFile || !groqKey || testTypes.length === 0}
            className="btn-action"
            style={{ marginLeft: '10px' }}
          >
            {isGenerating ? 'Generating Test Cases...' : 'Generate Test Cases'}
          </button>
        </div>

        {generatedTestPlan || generatedTestCases ? (
          <div className="results-panel">
            <h2>📄 Generated Documents</h2>

            {generatedTestPlan && (
              <div className="result-section">
                <h3>Test Plan</h3>
                <div className="result-preview">
                  <pre>{generatedTestPlan}</pre>
                </div>
                <button
                  onClick={downloadTestPlan}
                  className="btn-download"
                >
                  ⬇️ Download Test Plan
                </button>
              </div>
            )}

            {generatedTestCases && (
              <div className="result-section">
                <h3>Test Cases</h3>
                <div className="result-preview">
                  <pre>{generatedTestCases}</pre>
                </div>
                <button
                  onClick={downloadTestCases}
                  className="btn-download"
                >
                  ⬇️ Download Test Cases
                </button>
              </div>
            )}
          </div>
        ) : (
          <div className="results-panel empty-state">
            <p>Upload a PRD file, configure GROQ settings, select test types, then click generate to create test plan and test cases.</p>
          </div>
        )}
      </main>

      <footer className="app-footer">
        <p>B.L.A.S.T. Test Case Generator • Built with React • Follows B.L.A.S.T. Protocol</p>
      </footer>
    </div>
  );
}

export default App;